# Generated by Django 4.1.4 on 2023-03-06 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(default='Say something about yourself here.', max_length=400),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilePic',
            field=models.CharField(blank=True, default='https://th.bing.com/th/id/OIP.ybB2a0HimX1I-ybBY4pOPwHaHa?pid=ImgDet&rs=1', max_length=250, null=True),
        ),
    ]
