# Generated by Django 4.1.4 on 2023-03-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_profile_username_alter_profile_introduction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numFollower',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='numFollowing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(default='', max_length=400),
        ),
    ]
