# Generated by Django 4.1.4 on 2023-03-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>', max_length=80),
        ),
    ]
