# Generated by Django 4.1.4 on 2023-03-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
