# Generated by Django 4.1.4 on 2023-03-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_rename_likes_post_numlikes_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='userId',
            field=models.IntegerField(unique=True),
        ),
    ]
