# Generated by Django 4.1.4 on 2023-03-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_likes_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('chirpId', 'userId')},
        ),
    ]
